### ISSUE TITLE
Red Cost increase too fast

### ISSUE THREAD

**Issue by ModdedGamers** [Ikerstreamer/RGB-Idle#3]
The upgrade cost for red scales too quickly. How fast does it increase? I feel that it could be lowered to scale properly with progression.

**Comment by ModdedGamers** [comment]
@Ikerstreamer could you tell me where the cost increase lines are in main.js? Thanks!

**Comment by aarextiaokhiao** [comment]
The cost will increase a lot every 100 levela.

**Comment by ModdedGamers** [comment]
K. Thanks! That explains it, but it is still a bit too much.
