### ISSUE TITLE
Spliced Totals

### ISSUE THREAD

**Issue by Nessworthy** [Ikerstreamer/RGB-Idle#6]
Hi!

Spliced total numbers, while calculated based on the tier of colour, look a bit strange from the UI point of view. If I have 280M blue and splice, I would expect my spliced blue total to go up about 28M, not shoot up by over 3B! From the code, I can totally understand where it gets those totals from, but it just looks a bit strange while playing.

**Comment by Ikerstreamer** [comment]
I have also changed this in the next update to make it easier for the user, once again thx for letting me know.
