### ISSUE TITLE
Spectrum gain after 2

### ISSUE THREAD

**Issue by Nessworthy** [Ikerstreamer/RGB-Idle#7]
Hi!

From playing, it just looks like the first 2 spectrum you get from a play are attainable, but the required amount to get 3 spectrum is an insane jump up, especially considering the limited amount of upgrades before they start costing a lot more spectrum than you can feasibly attain without playing a super long time.

**Comment by Nessworthy** [comment]
For reference, if you give yourself 10k spectrum for all the unlocks, you end up with maybe 50 spectrum.
Considering the last upgrades cost spectrum in the thousands, maybe it just needs tweaking!

**Comment by Ikerstreamer** [comment]
I totally agree with you and have taken action to change this in the next update. Thx for supporting the project.
